### ISSUE TITLE
Colrow appears as LUID in map display for Indonesia

### ISSUE THREAD

**Issue by EstherBoere** [iiasa/GLOBIOM_GUI#2]
When selecting the yields in the map display for Indonesia, it looks like the map displays in LUID resolution rather than the colrow resolution. However, in the table settings it does mention CR on the column.

**Comment by acjbrouwer** [comment]
Counting the blocks as displayed and dividing by the longitudinal width of Indonesia (about 5100km) indicates the blocks are 1x1 degree instead of 0.5x0.5 degree. So no LU (2x2 degree).

However the Shapefile used to generate the GGIG coordinate file is definitely 0.5x0.5 degree (720 columns, 360 rows), with keys running from CR001001 to CR720360. This looks like a Java-side issue.

**Comment by acjbrouwer** [comment]
Fixed in commit a5ffc56ed841b103752b4c8ff50aed8412c4107e
